# **Essential Python for DA**

# OOP

In [ ]:
from random import randint

class ATM:
  def __init__(self,account_name,bank_name, initial):
    self.account_name = account_name
    self.bank_name = bank_name
    self.balance = initial

  ## string repesentation
  def __str__(self):
    return f"This is an account of {self.account_name}, bank: {self.bank_name}"

  ## method => function
  def check_balance(self):
    print(f"Balance: {self.balance} THB")

  def deposit(self,money):
    self.balance += money
    print(f"Deposit successfully: {money} THB, you new balance: {self.balance} THB")

  def withdraw(self,money):
    self.balance -= money
    print(f"Withdraw successfully: {money} THB, you new balance: {self.balance} THB")

  def get_OTP(self):
    otp = randint(1001,9999)
    print(f"Your OTP: {otp} This OTP will be available in the next 2 minutes.")


In [ ]:
## create an intance from ATM class
acc1 = ATM("New","SCB",500)

In [ ]:
acc1.deposit(2000)

Deposit successfully: 2000 THB, you new balance: 2500 THB


In [ ]:
# code is for human
print(acc1)

This is an account of New, bank: SCB


In [ ]:
acc1.check_balance()

Balance: 2500 THB


In [ ]:
acc1.deposit(500)

Deposit successfully: 500 THB, you new balance: 3000 THB


In [ ]:
acc1.withdraw(1000)

Withdraw successfully: 1000 THB, you new balance: 2000 THB


In [ ]:
acc1.get_OTP()

Your OTP: 5099 This OTP will be available in the next 2 minutes.


# Try Except Block

In [ ]:
try:
  1/5
except ZeroDivisionError:
  print("cannot divide by zero ")
except NameError:
  print("variable not defined")
else:
  print("Done")
finally:
  print("Complete!")

Done
Complete!


In [ ]:
# import csv
import csv

In [ ]:
try:
  file = open("friend.csv")

  data = csv.reader(file)

  for row in data:
    print(row)

  file.close()
except FileNotFoundError:
  print("File not found.")

['id', 'name', 'age', 'city']
['1', 'new', '23', 'bangkok']
['2', 'bamm', '22', 'london']
['3', 'john', '25', 'tokyo']


In [ ]:
file = open("friend.csv")

data = csv.reader(file)

for row in data:
  print(row)

file.close()

['id', 'name', 'age', 'city']
['1', 'new', '23', 'bangkok']
['2', 'bamm', '22', 'london']
['3', 'john', '25', 'tokyo']


In [ ]:
## context manager
result = []
## open and close file automatically
try:
  with open("friend.csv") as file:
    data = csv.reader(file)
    for row in data:
      result.append(row)

except :
  print("file not found")
else:
  print("load data successfully")
finally:
  print(result)

load data successfully
[['id', 'name', 'age', 'city'], ['1', 'new', '23', 'bangkok'], ['2', 'bamm', '22', 'london'], ['3', 'john', '25', 'tokyo']]


In [ ]:
# import csv (data analyst style)
import pandas as pd



id  name  age     city
0   1   new   23  bangkok
1   2  bamm   22   london
2   3  john   25    tokyo

In [ ]:
!cat friend.csv

id,name,age,city
1,new,23,bangkok
2,bamm,22,london
3,john,25,tokyo


In [ ]:
try :

  df = pd.read_csv("friend.csv")
except :
  print("a little error")

In [ ]:
df

id  name  age     city
0   1   new   23  bangkok
1   2  bamm   22   london
2   3  john   25    tokyo

In [ ]:
## write csv file using pandas
df.to_csv("newCSVFlie")

In [ ]:
## write csv using csv module
import csv

In [ ]:
col_names = ["food_id","food","pirce"]

In [ ]:
data = [
    [1,"pizza",200],
    [2, "french fried", 50],
    [3,"coke",20]

]

In [ ]:
with open("food.csv","w") as file:
  writer = csv.writer(file)
  writer.writerow(col_names)
  writer.writerows(data)

In [ ]:
!cat food.csv

food_id,food,pirce
1,pizza,200
2,french fried,50
3,coke,20


JSON

In [ ]:
## json = dictinory in python

import json

with open("data.json") as jsonfile:
    result = json.load (jsonfile)

print(result)

JSONDecodeError: Invalid control character at: line 3 column 15 (char 25)

# **API**
Application Programming Interface




In [ ]:
# import module
from requests import get

url = "https://swapi.dev/api/people/2"
response = get(url)

## 200 = ok
print(response.status_code)

200


In [ ]:
## see data that get back server
print(response.json())

{'name': 'C-3PO', 'height': '167', 'mass': '75', 'hair_color': 'n/a', 'skin_color': 'gold', 'eye_color': 'yellow', 'birth_year': '112BBY', 'gender': 'n/a', 'homeworld': 'https://swapi.dev/api/planets/1/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'species': ['https://swapi.dev/api/species/2/'], 'vehicles': [], 'starships': [], 'created': '2014-12-10T15:10:51.357000Z', 'edited': '2014-12-20T21:17:50.309000Z', 'url': 'https://swapi.dev/api/people/2/'}


In [ ]:
print(response.json()["name"])

Owen Lars


In [ ]:
# import module
from requests import get
from time import sleep
import pandas as pd

url2 = "https://swapi.dev/api/people/"
starwar = []
for i in range(5):
  index = i + 1
  new_url = url2+str(index)
  resp = get(new_url).json()
  name = resp["name"]
  height = resp["height"]
  weight = resp["mass"]
  gender = resp["gender"]
  homeworld = resp["homeworld"]
  data = {
      "name":name,
      "height":height,
      "weight":weight,
      "gender":gender,
      "homeworld":homeworld
  }

  #result = print(name,height,weight,gender,homeworld)
  starwar.append(data)

  sleep(1)


In [ ]:
df_starwar = pd.DataFrame(starwar)
df_starwar

name height weight  gender                         homeworld
0  Luke Skywalker    172     77    male  https://swapi.dev/api/planets/1/
1           C-3PO    167     75     n/a  https://swapi.dev/api/planets/1/
2           R2-D2     96     32     n/a  https://swapi.dev/api/planets/8/
3     Darth Vader    202    136    male  https://swapi.dev/api/planets/1/
4     Leia Organa    150     49  female  https://swapi.dev/api/planets/2/

In [ ]:
df_starwar.to_csv("starwar.csv",index = False)

In [ ]:
url1 = "https://swapi.dev/api/planets/1/"
home = get(url1)
print(home.status_code)
print(home.json())

200
{'name': 'Tatooine', 'rotation_period': '23', 'orbital_period': '304', 'diameter': '10465', 'climate': 'arid', 'gravity': '1 standard', 'terrain': 'desert', 'surface_water': '1', 'population': '200000', 'residents': ['https://swapi.dev/api/people/1/', 'https://swapi.dev/api/people/2/', 'https://swapi.dev/api/people/4/', 'https://swapi.dev/api/people/6/', 'https://swapi.dev/api/people/7/', 'https://swapi.dev/api/people/8/', 'https://swapi.dev/api/people/9/', 'https://swapi.dev/api/people/11/', 'https://swapi.dev/api/people/43/', 'https://swapi.dev/api/people/62/'], 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'created': '2014-12-09T13:50:49.641000Z', 'edited': '2014-12-20T20:58:18.411000Z', 'url': 'https://swapi.dev/api/planets/1/'}


None


In [ ]:
## Homework
# 02 find public API

# **Numpy & Pandas**
numerical python

pandas dataframe

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
nums = [1,20,25,30,100]

In [ ]:
arr_nums = np.array(nums)

In [ ]:
np.sum(arr_nums)

176

In [ ]:
print(
    np.sum(arr_nums),
    np.mean(arr_nums),
    np.median(arr_nums),
    np.max(arr_nums),
    np.min(arr_nums),
    np.std(arr_nums)
)

176 35.2 25.0 100 1 33.85498486190771


In [ ]:
## vector
m1 = np.array([
    [1,2],
    [3,4]])

In [ ]:
m1 + 100

array([[101, 102],
       [103, 104]])

In [ ]:
# element wise computation
m1 + m1

array([[2, 4],
       [6, 8]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.arange(1,101,1) # = 1:100 in R


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
np.linspace(1,101,5)

array([  1.,  26.,  51.,  76., 101.])

In [ ]:
# matrix dot notation
m2 = np.array([
    [5,5],
    [3,2]
])

In [ ]:
m1.dot(m2)

array([[11,  9],
       [27, 23]])

In [ ]:
## create dataframe from scratch
data = {
    "id":[1,2,3],
    "name":["New","Bamm","Ton"],
    "city":["BKK","Tokyo","London"]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

id  name    city
0   1   New     BKK
1   2  Bamm   Tokyo
2   3   Ton  London

In [ ]:
df["name"][2]

'Ton'

In [ ]:
df["age"] = [23,22,4]

In [ ]:
df

id  name    city  age
0   1   New     BKK   23
1   2  Bamm   Tokyo   22
2   3   Ton  London    4

In [ ]:
df.drop("age",axis = 1)


id  name    city
0   1   New     BKK
1   2  Bamm   Tokyo
2   3   Ton  London

In [ ]:
import pandas as pd
df1 = pd.read_csv("sample-store.csv")

In [ ]:
df1.head()

In [ ]:
df1.tail(3)

In [ ]:
df1.columns #attribute

In [ ]:
df1.info() # metod

In [ ]:
df1.shape

In [ ]:
## query() = filter rows with condition

## clean dataframe column names
df1.columns

In [ ]:
col_names = list(df1.columns)
for name in col_names:
  print(name.lower().replace(" ","_").replace("-","_"))

In [ ]:
clean_col_names = [name.lower().replace(" ","_").replace("-","_")
                  for name in col_names]
print(clean_col_names)

In [ ]:
df1.columns = clean_col_names
df1.head()

In [ ]:
## data transfromation ( R dplyr)
df1[["customer_id","customer_name"]].head(3)

In [ ]:
df2 = df1[df1["customer_name"] == "Claire Gute"].head(10)
df2

In [ ]:
df1[df1["customer_name"] == "Claire Gute"][["order_date","customer_id","customer_name"]]

In [ ]:
## query
df1.query("city == 'Los Angeles' and category == 'Furniture' and sub_category == 'Tables' ")[["customer_name","segment","city"]]

In [ ]:
## aggregate data
df1.groupby(["Segment","Region"])[["Sales","Profit"]].sum()

Sales      Profit
Segment     Region                          
Consumer    Central  252031.4340   8564.0481
            East     350908.1670  41190.9843
            South    195580.9710  26913.5728
            West     362880.7730  57450.6040
Corporate   Central  157995.8128  18703.9020
            East     200409.3470  23622.5789
            South    121885.9325  15215.2232
            West     225855.2745  34437.4299
Home Office Central   91212.6440  12438.4124
            East     127463.7260  26709.2168
            South     74255.0015   4620.6343
            West     136721.7770  16530.4150

In [ ]:
## aggregate data
result = df1.groupby(["segment","region"])[["sales","profit"]]\
.agg(["sum","mean"])\
.reset_index()

result.to_csv("agg_data.csv")

In [ ]:
## aggregate data
result = df1.query("region == 'West'").groupby(["segment","region"])[["sales","profit"]]\
.agg(["sum","mean"])\
.reset_index()
result

##**Load data from SQL**

In [ ]:
import sqlite3
import pandas as pd

## create connection
con = sqlite3.connect("chinook.db")

In [ ]:
con

In [ ]:
cust = pd.read_sql("select * from customers where country = 'USA'",con)

cust

In [ ]:
con.close()

##Sklearn Foundation
Model:linear regression

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
import pandas as pd
import numpy as np

model1 = LinearRegression()


In [ ]:
## read csv data from github mtcars
url = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"

mtcars = pd.read_csv(url)

In [ ]:
# ML Workflow
## 4 steps: split> ttrain > test > evaluate
y = mtcars["mpg"]
X = mtcars[["hp","wt","am"]]

# 1. train_test_spilt
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=19
)

## 2. train model
model = DecisionTreeRegressor()
model.fit(X_train,y_train) ## model fitting

# 3. score
train_error = model.score(X_train, y_train)

# 4. evaluation
test_error = model.score(X_test, y_test)

print(train_error, test_error)

In [ ]:
def rmse(actual, pred):
  error = actual - pred
  return np.sqrt(np.mean((error**2)))

In [ ]:
actual = np.array([1,2,3])
pred = np.array([1,2,1])

rmse(actual,pred)